using Busniess_Layer;
using System.Data;
using System.Diagnostics.Contracts;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace Presentation_Layer__WPF_
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            WindowState = WindowState.Maximized;
            _RefreshContactsList();
        }



        void _RefreshContactsList()
        {
            DG.ItemsSource = null;
            DG.ItemsSource = clsContacts.GetAllContacts().DefaultView;
        }



        private void btnAdd_Click(object sender, RoutedEventArgs e)
        {
            int ContactID = -1;
            Window window = new AddEditForm(ContactID);
            window.ShowDialog();
            _RefreshContactsList();

        }




        private void EditMenuItem_Click(object sender, RoutedEventArgs e)
        {
            var row = DG.SelectedItem as DataRowView;
            if (row != null)
            {
                int ContactID = (int)row["ContactID"];
                Window window = new AddEditForm(ContactID);
                window.ShowDialog();
                _RefreshContactsList();
            }
        }
        private void DeleteMenuItem_Click(object sender, RoutedEventArgs e)
        {
            var row = DG.SelectedItem as DataRowView;

            if (row != null)
            {
                int _ContactID = (int)row["ContactID"];

                if (MessageBox.Show(
                    "Are you sure you want to delete contact [" + _ContactID + "]",
                    "Confirm Delete",
                    MessageBoxButton.YesNo) == MessageBoxResult.Yes)
                {
                    if (clsContacts.DeleteContact(_ContactID))
                    {
                        MessageBox.Show("Contact Deleted Successfully.");
                        _RefreshContactsList();
                    }
                    else
                    {
                        MessageBox.Show("Contact is not deleted.");
                    }
                }
            }
        }

        private void DG_Loaded(object sender, RoutedEventArgs e)
        {
            _RefreshContactsList();
        }
        private void DG_LoadingRow(object sender, DataGridRowEventArgs e)
        {
            e.Row.Header = (e.Row.GetIndex() + 1).ToString();
        }
        private void DG_AutoGeneratedColumns(object sender, EventArgs e)
        {

        }
    }
}